services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    user: "redis:redis"
  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5437:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: outline
    user: "postgres:postgres"
